### PR TITLE
fix(spans): adhere attribute name to otel semver

### LINKED ISSUE #344: http - align OTEL http attributes with latest standard
to maintain compatibility with external tooling we should make sure our attribute respect the latest (stable) semantic conventions. When we initially implemented things, the spec was still in draft. The following attributes need to be renamed in the middleware handlers and in the request adapter:
htttp.status_code => http.response.status_code
http.response_content_length => http.response.body.size
http.request_content_length => http.request.body.size
http.flavor => network.protocol.name
http.response_content_type => http.response.header.content-type
http.request_content_type => http.request.header.content-type
http.method => http.request.method
http.host => url.scheme
http.scheme => server.address
http.uri => url.full
http.uri_template => url.uri_template

link to the spec for more information https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/
related https://github.com/microsoftgraph/msgraph-sdk-design/pull/108

### PR DESCRIPTION
**Pull request by Strazz1337**
Updates the http span attributes to match with the updated OTEL specification.

closes #344

### CODE REVIEW

**Comment by Strazz1337** [comment]
@microsoft-github-policy-service agree

**Review by baywet — DISMISSED** [review]
Thanks for the contribution!

**Comment by baywet** [comment]
Can you also add an entry to the changelog (patch, today, changed) and bump the version in the directory file please?

**Review by baywet — APPROVED** [review]
Thank you for making the changes!

**Comment by baywet** [comment]
@Strazz1337 if you're comfortable in other languages and want to contribute some more, we have the same in:
- Java https://github.com/microsoft/kiota-java/issues/1540
- Python https://github.com/microsoft/kiota-http-python/issues/409
- Go https://github.com/microsoft/kiota-http-go/issues/182

**Pull request merged**
